name: 'Compress public'

on:
  push:
    paths:
      - 'public/**.png'
      - '!public/icons/**'
      - '!public/**/__*'
      - '!public/**/*-2xl.png'
      - '!public/**/*-xl.png'
      - '!public/**/*-lg.png'
      - '!public/**/*-md.png'
      - '!public/**/*-sm.png'

  workflow_dispatch:

concurrency:
  group: compress-public-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compress:
    name: Compress public
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1.8.1
        with:
          app-id: ${{ secrets.CONTINUOUS_INTEGRATION_BOT_ID }}
          private-key: ${{ secrets.CONTINUOUS_INTEGRATION_BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Install Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4.2.0
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Compress public
        run: node --run compress:public

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "ci: compress public"
          git push
